import type {
  CartoonRecord,
  CutawayRecord,
  CutawaySegmentRecord,
  DaisyBellRecord,
  EpisodeRecord,
  FilmSceneRecord,
  SequenceRecord,
  SeriesCharacterRecord,
  StaffMemberRecord,
} from './schemas';

function toTsString(value: string): string {
  return JSON.stringify(value);
}

function toTsStringArray(values: string[]): string {
  return `[${values.map((value) => toTsString(value)).join(', ')}]`;
}

export function emitSongsModule(
  songs: Array<{
    id: string;
    title: string;
    genre: string;
    description: string;
    episode: string;
    tags: string[];
    instrumental: boolean;
    sourceFile: string;
    stylePrompt: string;
    lyrics: string | null;
    notes: string | null;
    audioFile: string | null;
  }>,
): string {
  const linked = songs
    .map((song) => song.audioFile)
    .filter((file): file is string => Boolean(file));

  const songBlocks = songs
    .map((song) => {
      const audioLine = song.audioFile ? `,\n    audioFile: ${toTsString(song.audioFile)}` : '';

      return `  {
    id: ${toTsString(song.id)},
    title: ${toTsString(song.title)},
    genre: ${toTsString(song.genre)},
    description: ${toTsString(song.description)},
    episode: ${toTsString(song.episode)},
    stylePrompt: ${toTsString(song.stylePrompt)},
    lyrics: ${song.lyrics ? toTsString(song.lyrics) : 'null'},
    notes: ${song.notes ? toTsString(song.notes) : 'null'},
    instrumental: ${song.instrumental},
    tags: ${toTsStringArray(song.tags)},
    sourceFile: ${toTsString(song.sourceFile)}${audioLine}
  }`;
    })
    .join(',\n');

  return `// AUTO-GENERATED by scripts/content-index — do not edit
import type { Song } from '../types';

export const linkedAudioFilenames = new Set<string>([
${linked.map((file) => `  ${toTsString(file)},`).join('\n')}
]);

export const songs: Song[] = [
${songBlocks}
];
`;
}

/** A pre-rendered TS expression (an imported asset binding) inside an emitted literal. */
class Raw {
  constructor(readonly code: string) {}
}

interface RecordsSpec {
  /** Prefix for generated image import names, e.g. `cartoonImg`. */
  importPrefix: string;
  /** Source key holding a repo-relative image path → emitted key holding the imported URL. */
  imageKeys?: Record<string, string>;
  /** Source-only keys that codegen resolves elsewhere and never emits. */
  omit?: readonly string[];
  /** Keys whose values are emitted as compact single-line JSON (large opaque payloads). */
  inline?: readonly string[];
}

const identifier = /^[A-Za-z_$][\w$]*$/;

function formatLiteral(value: unknown, depth: number): string {
  if (value instanceof Raw) return value.code;
  if (value === null || typeof value !== 'object') return JSON.stringify(value);

  const pad = '  '.repeat(depth + 1);
  const closePad = '  '.repeat(depth);

  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    if (value.every((item) => typeof item === 'string')) {
      return `[${value.map((item) => JSON.stringify(item)).join(', ')}]`;
    }
    return `[\n${value.map((item) => `${pad}${formatLiteral(item, depth + 1)},`).join('\n')}\n${closePad}]`;
  }

  const entries = Object.entries(value);
  if (entries.length === 0) return '{}';
  return `{\n${entries
    .map(([key, item]) => {
      const name = identifier.test(key) ? key : JSON.stringify(key);
      return `${pad}${name}: ${formatLiteral(item, depth + 1)},`;
    })
    .join('\n')}\n${closePad}}`;
}

/**
 * Emits records generically from their own keys, so a field added to a Zod schema reaches the
 * generated module without touching this file. Only image paths (→ bundler imports) and
 * source-only keys are special-cased.
 */
function emitRecords(
  records: readonly object[],
  spec: RecordsSpec,
): { literal: string; importLines: string } {
  const imports = new Map<string, string>();
  const omit = new Set(spec.omit ?? []);
  const inline = new Set(spec.inline ?? []);
  const imageKeys = spec.imageKeys ?? {};

  const resolve = (value: unknown): unknown => {
    if (Array.isArray(value)) return value.map(resolve);
    if (value === null || typeof value !== 'object') return value;
    const out: Record<string, unknown> = {};
    for (const [key, item] of Object.entries(value)) {
      if (item === undefined || omit.has(key)) continue;
      const imageKey = imageKeys[key];
      if (imageKey && typeof item === 'string') {
        let alias = imports.get(item);
        if (!alias) {
          alias = `${spec.importPrefix}${imports.size}`;
          imports.set(item, alias);
        }
        out[imageKey] = new Raw(alias);
      } else if (inline.has(key)) {
        out[key] = new Raw(JSON.stringify(item));
      } else {
        out[key] = resolve(item);
      }
    }
    return out;
  };

  const resolved = records.map(resolve);
  const importLines = [...imports.entries()]
    .map(([path, alias]) => `import ${alias} from '../../../${path}';`)
    .join('\n');

  return { literal: formatLiteral(resolved, 0), importLines };
}

function emitModule(
  importLines: string,
  typeImport: string,
  exportName: string,
  typeName: string,
  literal: string,
): string {
  const imports = importLines ? `${importLines}\n\n` : '';
  return `// AUTO-GENERATED by scripts/content-index — do not edit
${imports}import type { ${typeImport} } from '../types';

export const ${exportName}: ${typeName}[] = ${literal};
`;
}

const stillKeys = { stillImagePath: 'stillUrl' } as const;
const pathKeys = { imagePath: 'imageUrl' } as const;

export function emitCutawaysModule(
  cutaways: Array<CutawayRecord & { segments: CutawaySegmentRecord[] }>,
): {
  code: string;
} {
  const { literal, importLines } = emitRecords(cutaways, {
    importPrefix: 'cutawayImg',
    imageKeys: stillKeys,
    omit: ['segmentsSource', 'segmentStills'],
  });
  return {
    code: emitModule(
      importLines,
      'CutawaySuggestion',
      'cutawaySuggestions',
      'CutawaySuggestion',
      literal,
    ),
  };
}

export function emitGalleryModule(scenes: FilmSceneRecord[]): string {
  const { literal, importLines } = emitRecords(scenes, {
    importPrefix: 'galleryImg',
    imageKeys: pathKeys,
  });
  return emitModule(importLines, 'FilmScene', 'filmScenes', 'FilmScene', literal);
}

export function emitCharactersModule(characters: SeriesCharacterRecord[]): string {
  const { literal, importLines } = emitRecords(characters, {
    importPrefix: 'characterImg',
    imageKeys: pathKeys,
  });
  return emitModule(importLines, 'SeriesCharacter', 'seriesCharacters', 'SeriesCharacter', literal);
}

export function emitDaisyBellModule(data: DaisyBellRecord): string {
  const { literal, importLines } = emitRecords(data.frames, {
    importPrefix: 'daisyImg',
    imageKeys: pathKeys,
  });
  const imports = importLines ? `${importLines}\n\n` : '';

  return `// AUTO-GENERATED by scripts/content-index — do not edit
${imports}import type { DaisyBellFrame, DaisyBellSequenceBeat, DaisyBellSight } from '../types';

export const daisyBellMeta = ${JSON.stringify(data.meta, null, 2)} as const;

export const daisyBellSubjectLock = ${toTsString(data.subjectLock)};

export const daisyBellStylish1890s = ${toTsString(data.stylish1890s)};

export const daisyBellWorking1890s = ${toTsString(data.working1890s)};

export const daisyBellAudioFile = daisyBellMeta.audioFile;

export const daisyBellSequence: DaisyBellSequenceBeat[] = ${JSON.stringify(data.sequence, null, 2)};

export const daisyBellSights: DaisyBellSight[] = ${JSON.stringify(data.sights, null, 2)};

export const daisyBellFrames: DaisyBellFrame[] = ${literal};
`;
}

export function emitStaffModule(staff: StaffMemberRecord[]): string {
  const { literal } = emitRecords(staff, { importPrefix: 'staffImg' });
  return emitModule('', 'StaffRecord', 'staffRecords', 'StaffRecord', literal);
}

export function emitEpisodesModule(episodes: EpisodeRecord[]): string {
  const { literal } = emitRecords(episodes, { importPrefix: 'episodeImg' });
  return emitModule('', 'EpisodeRecord', 'episodeRecords', 'EpisodeRecord', literal);
}

export function emitCartoonsModule(cartoons: CartoonRecord[]): string {
  const { literal, importLines } = emitRecords(cartoons, {
    importPrefix: 'cartoonImg',
    imageKeys: stillKeys,
  });
  return emitModule(importLines, 'CartoonRecord', 'cartoonRecords', 'CartoonRecord', literal);
}

export function emitSequencesModule(sequences: SequenceRecord[]): string {
  const { literal, importLines } = emitRecords(
    sequences.map((sequence) => ({
      ...sequence,
      renderer: sequence.graph ? 'graph' : 'custom',
    })),
    { importPrefix: 'sequenceImg', imageKeys: stillKeys, inline: ['graph'] },
  );
  return emitModule(importLines, 'SequenceRecord', 'sequenceRecords', 'SequenceRecord', literal);
}
