function toTsString(value: string): string {
  return JSON.stringify(value);
}

function toTsStringArray(values: string[]): string {
  return `[${values.map((value) => toTsString(value)).join(', ')}]`;
}

export function emitSongsModule(songs: Array<{
  id: string;
  title: string;
  genre: string;
  description: string;
  episode: string;
  tags: string[];
  instrumental: boolean;
  sourceFile: string;
  stylePrompt: string;
  lyrics: string | null;
  notes: string | null;
  audioFile: string | null;
}>): string {
  const linked = songs
    .map((song) => song.audioFile)
    .filter((file): file is string => Boolean(file));

  const songBlocks = songs
    .map((song) => {
      const audioLine = song.audioFile
        ? `,\n    audioFile: ${toTsString(song.audioFile)}`
        : '';

      return `  {
    id: ${toTsString(song.id)},
    title: ${toTsString(song.title)},
    genre: ${toTsString(song.genre)},
    description: ${toTsString(song.description)},
    episode: ${toTsString(song.episode)},
    stylePrompt: ${toTsString(song.stylePrompt)},
    lyrics: ${song.lyrics ? toTsString(song.lyrics) : 'null'},
    notes: ${song.notes ? toTsString(song.notes) : 'null'},
    instrumental: ${song.instrumental},
    tags: ${toTsStringArray(song.tags)},
    sourceFile: ${toTsString(song.sourceFile)}${audioLine}
  }`;
    })
    .join(',\n');

  return `// AUTO-GENERATED by scripts/content-index — do not edit
import type { Song } from '../types';

export const linkedAudioFilenames = new Set<string>([
${linked.map((file) => `  ${toTsString(file)},`).join('\n')}
]);

export const songs: Song[] = [
${songBlocks}
];
`;
}

function emitCutawaySegment(segment: {
  id: string;
  label: string;
  start: string;
  end: string;
  durationSec: number;
  onScreen: string;
  lyrics: string;
  musicCue: string;
  grokImaginePrompt: string;
  geminiOmniPrompt: string;
  promptVariations: string[];
  stillImagePath?: string;
}, imageBindings: Map<string, string>): string {
  const stillLine = segment.stillImagePath
    ? `stillUrl: ${imageBindings.get(segment.stillImagePath)},`
    : '';

  return `      {
        id: ${toTsString(segment.id)},
        label: ${toTsString(segment.label)},
        start: ${toTsString(segment.start)},
        end: ${toTsString(segment.end)},
        durationSec: ${segment.durationSec},
        onScreen: ${toTsString(segment.onScreen)},
        lyrics: ${toTsString(segment.lyrics)},
        musicCue: ${toTsString(segment.musicCue)},
        grokImaginePrompt: ${toTsString(segment.grokImaginePrompt)},
        geminiOmniPrompt: ${toTsString(segment.geminiOmniPrompt)},
        promptVariations: ${toTsStringArray(segment.promptVariations)},
        ${stillLine}
      }`;
}

function emitJsonValue(value: unknown, indent: number): string {
  const pad = ' '.repeat(indent);
  return JSON.stringify(value, null, 2)
    .split('\n')
    .map((line, index) => (index === 0 ? line : `${pad}${line}`))
    .join('\n');
}

export function emitCutawaysModule(
  cutaways: Array<{
    id: string;
    kind: string;
    title: string;
    status: string;
    runtime: string;
    episode: string;
    songId: string;
    songTitle: string;
    summary: string;
    visualArc: string;
    tags: string[];
    sightBank?: Array<{
      id: string;
      title: string;
      category: string;
      lane: string;
      prompt: string;
      description: string;
    }>;
    segments: Array<{
      id: string;
      label: string;
      start: string;
      end: string;
      durationSec: number;
      onScreen: string;
      lyrics: string;
      musicCue: string;
      grokImaginePrompt: string;
      geminiOmniPrompt: string;
      promptVariations: string[];
      stillImagePath?: string;
    }>;
  }>,
): { code: string; imageImports: Map<string, string> } {
  const imageImports = new Map<string, string>();
  let importIndex = 0;

  for (const cutaway of cutaways) {
    for (const segment of cutaway.segments) {
      if (segment.stillImagePath && !imageImports.has(segment.stillImagePath)) {
        imageImports.set(segment.stillImagePath, `cutawayImg${importIndex++}`);
      }
    }
  }

  const importLines = [...imageImports.entries()]
    .map(([path, alias]) => `import ${alias} from '../../../${path}';`)
    .join('\n');

  const blocks = cutaways
    .map((cutaway) => {
      const segments = cutaway.segments
        .map((segment) => emitCutawaySegment(segment, imageImports))
        .join(',\n');

      const sightBankLine = cutaway.sightBank?.length
        ? `\n    sightBank: ${emitJsonValue(cutaway.sightBank, 4)},`
        : '';

      return `  {
    id: ${toTsString(cutaway.id)},
    kind: ${toTsString(cutaway.kind)},
    title: ${toTsString(cutaway.title)},
    status: ${toTsString(cutaway.status)},
    runtime: ${toTsString(cutaway.runtime)},
    episode: ${toTsString(cutaway.episode)},
    songId: ${toTsString(cutaway.songId)},
    songTitle: ${toTsString(cutaway.songTitle)},
    summary: ${toTsString(cutaway.summary)},
    visualArc: ${toTsString(cutaway.visualArc)},
    tags: ${toTsStringArray(cutaway.tags)},${sightBankLine}
    segments: [
${segments}
    ],
  }`;
    })
    .join(',\n');

  const code = `// AUTO-GENERATED by scripts/content-index — do not edit
${importLines}

import type { CutawaySuggestion } from '../types';

export const cutawaySuggestions: CutawaySuggestion[] = [
${blocks}
];
`;

  return { code, imageImports };
}

export function emitGalleryModule(
  scenes: Array<{
    id: string;
    imageKind: string;
    episode: string;
    title: string;
    prompt: string;
    promptVariations: string[];
    imagePath?: string;
    mediaType: string;
    musicCue: string;
    musicStyle: string;
    description: string;
    theme: string;
    tags: string[];
  }>,
): string {
  const imageImports = new Map<string, string>();
  let importIndex = 0;

  for (const scene of scenes) {
    if (scene.imagePath && !imageImports.has(scene.imagePath)) {
      imageImports.set(scene.imagePath, `galleryImg${importIndex++}`);
    }
  }

  const importLines = [...imageImports.entries()]
    .map(([path, alias]) => `import ${alias} from '../../../${path}';`)
    .join('\n');

  const blocks = scenes
    .map((scene) => {
      const imageLine = scene.imagePath
        ? `imageUrl: ${imageImports.get(scene.imagePath)},`
        : '';

      return `  {
    id: ${toTsString(scene.id)},
    imageKind: ${toTsString(scene.imageKind)},
    episode: ${toTsString(scene.episode)},
    title: ${toTsString(scene.title)},
    prompt: ${toTsString(scene.prompt)},
    promptVariations: ${toTsStringArray(scene.promptVariations)},
    ${imageLine}
    mediaType: ${toTsString(scene.mediaType)},
    musicCue: ${toTsString(scene.musicCue)},
    musicStyle: ${toTsString(scene.musicStyle)},
    description: ${toTsString(scene.description)},
    theme: ${toTsString(scene.theme)},
    tags: ${toTsStringArray(scene.tags)},
  }`;
    })
    .join(',\n');

  return `// AUTO-GENERATED by scripts/content-index — do not edit
${importLines}

import type { FilmScene } from '../types';

export const filmScenes: FilmScene[] = [
${blocks}
];
`;
}

export function emitCharactersModule(
  characters: Array<{
    id: string;
    name: string;
    nameNote?: string;
    role: string;
    episodes: string[];
    traits: string[];
    bio: string;
    props: string[];
    tags: string[];
    imagePath?: string;
  }>,
): string {
  const imageImports = new Map<string, string>();
  let importIndex = 0;

  for (const character of characters) {
    if (character.imagePath && !imageImports.has(character.imagePath)) {
      imageImports.set(character.imagePath, `characterImg${importIndex++}`);
    }
  }

  const importLines = [...imageImports.entries()]
    .map(([path, alias]) => `import ${alias} from '../../../${path}';`)
    .join('\n');

  const blocks = characters
    .map((character) => {
      const imageLine = character.imagePath
        ? `imageUrl: ${imageImports.get(character.imagePath)},`
        : '';
      const nameNoteLine = character.nameNote
        ? `nameNote: ${toTsString(character.nameNote)},`
        : '';

      return `  {
    id: ${toTsString(character.id)},
    name: ${toTsString(character.name)},
    ${nameNoteLine}
    role: ${toTsString(character.role)},
    episodes: ${toTsStringArray(character.episodes)},
    traits: ${toTsStringArray(character.traits)},
    bio: ${toTsString(character.bio)},
    props: ${toTsStringArray(character.props)},
    tags: ${toTsStringArray(character.tags)},
    ${imageLine}
  }`;
    })
    .join(',\n');

  return `// AUTO-GENERATED by scripts/content-index — do not edit
${importLines}

import type { SeriesCharacter } from '../types';

export const seriesCharacters: SeriesCharacter[] = [
${blocks}
];
`;
}

export function emitDaisyBellModule(data: {
  meta: {
    id: string;
    title: string;
    subtitle: string;
    duo: string;
    audioFile: string;
    conceptFile: string;
    slideshowUrl: string;
    pitch: string;
    constant: string;
  };
  subjectLock: string;
  stylish1890s: string;
  working1890s: string;
  sequence: Array<{ id: string; step: number; title: string; treatment: string; summary: string }>;
  sights: Array<{ id: string; lyricCue: string | null; title: string; description: string }>;
  frames: Array<{
    id: string;
    order: number;
    title: string;
    treatment: string;
    beat: string;
    description: string;
    prompt: string;
    imagePath?: string;
    tags: string[];
  }>;
}): string {
  const imageImports = new Map<string, string>();
  let importIndex = 0;

  for (const frame of data.frames) {
    if (frame.imagePath && !imageImports.has(frame.imagePath)) {
      imageImports.set(frame.imagePath, `daisyImg${importIndex++}`);
    }
  }

  const importLines = [...imageImports.entries()]
    .map(([path, alias]) => `import ${alias} from '../../../${path}';`)
    .join('\n');

  const frameBlocks = data.frames
    .map((frame) => {
      const imageLine = frame.imagePath
        ? `imageUrl: ${imageImports.get(frame.imagePath)},`
        : '';

      return `  {
    id: ${toTsString(frame.id)},
    order: ${frame.order},
    title: ${toTsString(frame.title)},
    treatment: ${toTsString(frame.treatment)},
    beat: ${toTsString(frame.beat)},
    description: ${toTsString(frame.description)},
    prompt: ${toTsString(frame.prompt)},
    ${imageLine}
    tags: ${toTsStringArray(frame.tags)},
  }`;
    })
    .join(',\n');

  return `// AUTO-GENERATED by scripts/content-index — do not edit
${importLines}

import type { DaisyBellFrame, DaisyBellSequenceBeat, DaisyBellSight } from '../types';

export const daisyBellMeta = ${JSON.stringify(data.meta, null, 2)} as const;

export const daisyBellSubjectLock = ${toTsString(data.subjectLock)};

export const daisyBellStylish1890s = ${toTsString(data.stylish1890s)};

export const daisyBellWorking1890s = ${toTsString(data.working1890s)};

export const daisyBellAudioFile = daisyBellMeta.audioFile;

export const daisyBellSequence: DaisyBellSequenceBeat[] = ${JSON.stringify(data.sequence, null, 2)};

export const daisyBellSights: DaisyBellSight[] = ${JSON.stringify(data.sights, null, 2)};

export const daisyBellFrames: DaisyBellFrame[] = [
${frameBlocks}
];
`;
}
